[package]
name = "poker-lib"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rust_poker = { path = "./rust_poker" }
playing-cards = { path = "./playing-cards", features = [] }